### PR TITLE
Add Dockerfile to project

### PR DESCRIPTION
**Pull request by drwl**
The integration tests require RVM to run. Without them they can't run.

Added Dockerfile to make it easier to run the project in an isolated environment.

### CODE REVIEW

**Comment by drwl** [comment]
cc @ctran was working on updating integration tests but found out that they:

1. haven't been running for some time, looks like they were [skipped started Feb 2014](https://github.com/ctran/annotate_models/commit/9540121243da58cad3ab3c0ba444f22445a995ed#diff-78ddf877ecc2a9344997ef077a77955a)
2. I don't have RVM installed locally and wanted an environment to debug the integration tests

**Comment by drwl** [comment]
Just realized I prematurely merged this. Should have gotten #708 working and added the Dockerfile and any other scripts there.

**Comment by cuong-now** [comment]
Is this for running things locally or on CI?

**Comment by drwl** [comment]
Would be for running the integration tests locally, for people who don't have rvm installed. The motivation for this was wanting to upgrade the integration specs, only to realize they haven't been running AND I'm not able to run them with my current setup (using rbenv).

**Pull request merged**
