### PR TITLE
Fix AnnotateRoutes.extract_magic_comments_from_array

### PR DESCRIPTION
**Pull request by nard-tech**
I replaced `Array#map` to `Array#each` because the mapped array is not used.

### CODE REVIEW

**Comment by nard-tech** [comment]
**WARNING**: Maybe this PR conflicts with #712.

**Comment by drwl** [comment]
> **WARNING**: Maybe this PR conflicts with #712.

What PR are you referring to? #712 is the one we're currently on.

**Comment by nard-tech** [comment]
@drwl Sorry, I want to say that may be this PR conflicts with #711. 
Now this PR #712 is conflicting, so I'll fix as soon as possible.

**Comment by nard-tech** [comment]
@drwl I fixed the conflict. I am sorry to trouble you, but please review again. Thank you.

**Comment by drwl** [comment]
> @drwl I fixed the conflict. I am sorry to trouble you, but please review again. Thank you.

No problem at all :) thanks for the time and effort you put into making the code base better 👍

**Pull request merged**
