### PR TITLE
Fixed Posgresql index tables with `public`.

### PR DESCRIPTION
**Pull request by ryanfox1985**
Hello,

I have a issue with my Postgresql database and the index annotations. 
In some models I added the table_name_prefix = 'public.' because I'm using different schemas and the annotation doesn't work because is looking for 'public.table_name' and doesn't exist.

Regards.

### CODE REVIEW

**Comment by ctran** [comment]
I would like to see a test case added for this if you don't mind.

**Comment by ryanfox1985** [comment]
Hi @ctran,

I will describe my case:

We are using `Postgresql` that supports to have multiples schemas (like `public` and `data_warehouse`).
Both schemas are sync (in structure) but we have some models using the `table_name_prefix` pointing to the `public` schema (like `Users`) because the data were the same. 

Let me add Rspec test to this part. 

Regards.

**Comment by ctran** [comment]
@ryanfox1985 Did you have a chance to add a test?

**Comment by ryanfox1985** [comment]
@ctran It's not easy to make a test xD. 
It will be the first that test the indexes.

**Comment by ryanfox1985** [comment]
@ctran it's ready.

**Pull request merged**
