### PR TITLE
Convert documentation files to Markdown

### PR DESCRIPTION
**Pull request by Vasfed**
This fixes https://github.com/ctran/annotate_models/issues/684

Also added notice about somewhat breaking change in 3.0 about models not being annotated by default when no option in config

### CODE REVIEW

**Comment by Vasfed** [comment]
Looks like github action is broken in master, travis build succeeded

**Comment by drwl** [comment]
@Vasfed thanks for this. Let me try and investigate what's going wrong in CI

**Comment by drwl** [comment]
@Vasfed I fixed CI issues in #698, can you rebase?

**Comment by Vasfed** [comment]
@drwl rebased, all is ok now

**Pull request merged**
