### PR TITLE
Do not include auto-generated foreign key names in schema dump

### LINKED ISSUE #404: Do not include auto-generated foreign key names in schema dump
My app uses Rails' [autogenerated random foreign key names](https://github.com/rails/rails/commit/8768305f20d12c40241396092a63e0d56269fefe).

## Problem
I frequently drop my dev database, regenerate it from migrations, and reseed it. Every time I do this, the foreign key names change, and `annotate_models` includes the changed names in its annotations.

ActiveRecord's SchemaDumper avoids this by [not dumping the name iff it matches the regex `/^fk_rails_[0-9a-f]{10}$/`](https://github.com/rails/rails/commit/8768305f20d12c40241396092a63e0d56269fefe#diff-e0d63791fb8e00fc467e7c47b74fb6d6R239):

```rb
if foreign_key.name !~ /^fk_rails_[0-9a-f]{10}$/
  parts << ('name: ' + foreign_key.name.inspect)
end
```

## Proposal

Would you be open to accepting a PR that adds a similar check to `annotate_models`?

### Considerations
I'm not sure how the formatting would work.

**Example (right now)**:
```rb
# Foreign Keys
#
#  fk_rails_3a1015a040  (user_id => users.id)
#  fk_rails_8941ddb7a6  (application_id => applications.id)
```

**Option 1** (proposal):
```rb
# Foreign Keys (random names elided)
#
#  fk_rails_XXXXXXXXXX  (user_id => users.id)
#  fk_rails_XXXXXXXXXX  (application_id => applications.id)
```

### PR DESCRIPTION
**Pull request by vergenzt**
Closes #404.

### CODE REVIEW

**Comment by vergenzt** [comment]
Hi @ctran: The tests and coverage check appear to pass, but semaphoreci and the Travis build are failing and I'm not sure why.

Any ideas?

**Comment by ctran** [comment]
Thanks for this.  I'll take a look to see sure why it failed the CI.

**Comment by vergenzt** [comment]
Thanks. I looked into it and it looked like all the errors in both systems came down to a dependency installation error: `ruby_dep-1.5.0 requires ruby version >= 2.2.5, which is incompatible with the current version, ruby 2.2.3p173`. However I didn't change any dependencies. :(

**Comment by ctran** [comment]
It's probably something that wasn't locked in the Gemfile :(

**Pull request merged**
