### PR TITLE
Play nicely with Rubocop's Layout/EmptyLineAfterMagicComment cop

### PR DESCRIPTION
**Pull request by betesh**

### CODE REVIEW

**Comment by chamnap** [comment]
+1

**Comment by stefanahman** [comment]
What's the status on this pull request?

**Comment by ctran** [comment]
It needs to be rebased and pass CI.

**Comment by betesh** [comment]
I deleted my fork and don't see a way to recover this branch now that its anonymous. I may just have to reapply the patches and open a new PR.  I'll give it a try later today unless someone here knows a more efficient way.

**Comment by eladitzhakian** [comment]
Thanks @betesh! Apparently this was actually solved in e84e22de8fb8fc4e251418bdc6875b1003c9898c but not yet released :)

**Comment by betesh** [comment]
Duplicates #573

**Pull request closed without merging**
