### PR TITLE
Added --ignore-models option for skipping models annotation

### PR DESCRIPTION
**Pull request by kamilbielawski**
Solves #357

### CODE REVIEW

**Comment by ctran** [comment]
Thanks for the PR but I was thinking of moving away from using the "exclude" options and use a "types" flag to allow individual types to be annotated.  It would have a default list of "types" to preserve the current behavior.  Want to implement that?

**Comment by kamilbielawski** [comment]
Yeah, I wasn't really convinced that adding this `--ignore-models` switch is a good idea but it was the simplest way to achieve functionality requested in the issue #357 .
I can implement `--types` flag, although it might take a while as I don't know when I find some time to do it.

**Comment by Hitabis** [comment]
Is this expected to be merged into the master branch? I'm also having the same problem described in #357 and would be happy to see this released soon.

**Comment by ctran** [comment]
The master branch merge will only happen when I do a release.  Can you point to the dev branch?

**Pull request closed without merging**
