### PR TITLE
Refactor by adding AnnotateRoutes::Helpers

### PR DESCRIPTION
**Pull request by nard-tech**
For further refactoring toward better architecture, I moved methods `.strip_annotations`, `.extract_magic_comments_from_array` and `.real_content_and_header_position` from `AnnotateRoutes` to `AnnotateRoutes::Helpers`.

### CODE REVIEW

**Comment by nard-tech** [comment]
cf. After refactoring, `AnnotateRoutes` will be like this draft. 

https://github.com/ctran/annotate_models/compare/develop...nard-tech:feature/refactor_annotate_routes/processors

I would like to refactor `AnnotateModels` too.

**Comment by drwl** [comment]
@nard-tech I'm confused as to what I should be reviewing. Should I just be reviewing commits 3a3b857, b1f7342, and 9cb8fc5?

**Comment by nard-tech** [comment]
@drwl I'm sorry to trouble you.
Please review only 3a3b857, b1f7342, and 9cb8fc5.

**Comment by nard-tech** [comment]
> cf. After refactoring, `AnnotateRoutes` will be like following link.
> 
> [develop...nard-tech:feature/refactor_annotate_routes/processors](https://github.com/ctran/annotate_models/compare/develop...nard-tech:feature/refactor_annotate_routes/processors) (draft)
> 
> I would like to refactor `AnnotateModels` too because its maintability is too bad.
> cf. https://codeclimate.com/github/ctran/annotate_models/lib/annotate/annotate_models.rb

@drwl 
This is just for reference.

**Pull request merged**
