### PR TITLE
Refactors

### PR DESCRIPTION
**Pull request by ryanfox1985**
Refactor annotate_routes.

Hi I reduced the Cyclomatic complexity, but it's so so difficult xD.
Have you time to see/register waffle.io and coveralls.io?

Regards!

### CODE REVIEW

**Comment by ctran** [comment]
Would you rebase all these commits into one or two?

**Comment by ryanfox1985** [comment]
Hi I created another pull request.

Have you time to register coveralls.io?

Regards!

2016-01-25 5:05 GMT+01:00 Cuong Tran <notifications@github.com>:

**Comment by ryanfox1985** [comment]
Same pull request than #332

**Comment by ctran** [comment]
I did register for coveralls.io but it kept crashing when I tried to add this repo.  Will give it another try.

**Pull request closed without merging**
