### PR TITLE
Preserve number of linefeeds after magic comments

### PR DESCRIPTION
**Pull request by b264**
Supercedes https://github.com/ctran/annotate_models/pull/495

Closes https://github.com/ctran/annotate_models/issues/509

Extension of https://github.com/ctran/annotate_models/issues/464

### CODE REVIEW

**Comment by ctran** [comment]
Was this merged?

**Comment by b264** [comment]
No; I found a bug and closed it before you merged it.  I haven't got time to fix it yet

**Comment by inspiredstuffs** [comment]
@b264 What is this bug about?

**Comment by b264** [comment]
https://github.com/ctran/annotate_models/issues/509

**Pull request closed without merging**
