### PR TITLE
Place column comments at the end of the line

### LINKED ISSUE #953: [Feature request] Place column comments at the end of the line
Hi, kudos for maintaining a most useful gem.

My problem is that column comments from Rails migrations are being placed in brackets just after column name, needlessly pushing everything else far to the right.

## What is happening
In migration I have this
```rb
add_column(
 :rfps, :options, :jsonb,
  null: false, default: {},
  comment: "Unified place for event options, suff like :public, *_flag, etc.",
)
```

Then annotation is something like this:
```rb
# == Schema Information
#
# Table name: rfps
#
#  id                                                                        :bigint           not null, primary key
#  deleted_at                                                                :datetime         indexed => [currency_id, bid_submission_deadline, state], indexed => [currency_id], indexed
#  options(Unified place for event options, suff like :public, *_flag, etc.) :jsonb            default({}), not null
```

## What would be better
Putting the comment at the end of the line would produce less whitespace in the middle of lines:
```rb
# == Schema Information
#
# Table name: rfps
#
#  id         :bigint    not null, primary key
#  deleted_at :datetime  indexed => [currency_id, bid_submission_deadline, state], indexed => [currency_id]
#  options    :jsonb     default({}), not null, comment => "Unified place for event options, suff like :public, *_flag, etc."
```

## Version
- annotate version 3.2.0
- rails version 6.0.4.8
- ruby version 2.7.5

### PR DESCRIPTION
**Pull request by Adeynack**
fixes #953.

By adding `--with-comment-column`, we can now see column comments at the end of the generated "table".

### CODE REVIEW

**Review by ctran — APPROVED** [review]
Thanks!

**Comment by Adeynack** [comment]
@ctran : My first open source contribution ever merged! 🎈🥳 🎈

**Comment by Adeynack** [comment]
@ctran : Are you planning a release of the GEM soon? I see the last one was early 2022. I just want to know if I go ahead targetting `develop` on GH in our GemFiles or wait a few days/weeks and keep using rubygems.

Thanks :-)

**Comment by ctran** [comment]
I'll work on that this weekend

**Comment by letiesperon** [comment]
@ctran is there any chance we release this one in a new gem version please? 🙏🏻

**Comment by jonmcelroy-appfolio** [comment]
@ctran Echoing again, any way to get a new release?

**Comment by kallmanation** [comment]
Sorry about adding to the noise; I came here because I was confused by the `--with-comment-column` option mentioned in the [readme](https://github.com/ctran/annotate_models) wasn't working.

Is releasing a new version of this awesome gem something we can help with @ctran?

**Comment by Adeynack** [comment]
@kallmanation : This seems to have been replaced by another GEM: [annotaterb](https://github.com/drwl/annotaterb). I opened a PR for a similar feature [here](https://github.com/drwl/annotaterb/pull/199).

**Pull request merged**
