### PR TITLE
Fix error: can't modify frozen String: "decimal"

### PR DESCRIPTION
**Pull request by n-rodriguez**
This PR fixes these errors due to the presence of `# frozen_string_literal: true` in files :

```sh
Unable to annotate app/models/camping.rb: can't modify frozen String: "decimal"
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:875:in `get_attributes'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:151:in `block in get_schema_info'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:149:in `each'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:149:in `get_schema_info'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:481:in `annotate'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:682:in `annotate_model_file'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:658:in `block in do_annotations'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:657:in `each'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:657:in `do_annotations'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/tasks/annotate_models.rake:56:in `block in <main>'
Unable to annotate app/models/camping.rb: no implicit conversion of nil into Array
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:682:in `concat'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:682:in `annotate_model_file'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:658:in `block in do_annotations'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:657:in `each'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:657:in `do_annotations'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/tasks/annotate_models.rake:56:in `block in <main>'
Unable to annotate app/models/camping_raw.rb: can't modify frozen String: "decimal"
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:875:in `get_attributes'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:151:in `block in get_schema_info'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:149:in `each'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:149:in `get_schema_info'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:481:in `annotate'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:682:in `annotate_model_file'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:658:in `block in do_annotations'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:657:in `each'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:657:in `do_annotations'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/tasks/annotate_models.rake:56:in `block in <main>'
Unable to annotate app/models/camping_raw.rb: no implicit conversion of nil into Array
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:682:in `concat'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:682:in `annotate_model_file'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:658:in `block in do_annotations'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:657:in `each'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:657:in `do_annotations'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/tasks/annotate_models.rake:56:in `block in <main>'
Unable to annotate app/models/user_profile.rb: can't modify frozen String: "decimal"
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:875:in `get_attributes'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:151:in `block in get_schema_info'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:149:in `each'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:149:in `get_schema_info'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:481:in `annotate'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:682:in `annotate_model_file'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:658:in `block in do_annotations'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:657:in `each'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:657:in `do_annotations'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/tasks/annotate_models.rake:56:in `block in <main>'
Unable to annotate app/models/user_profile.rb: no implicit conversion of nil into Array
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:682:in `concat'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:682:in `annotate_model_file'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:658:in `block in do_annotations'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:657:in `each'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/annotate/annotate_models.rb:657:in `do_annotations'
  /home/nicolas/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/annotate_models-786394947c04/lib/tasks/annotate_models.rake:56:in `block in <main>'
```

### CODE REVIEW

**Comment by n-rodriguez** [comment]
See https://github.com/ctran/annotate_models/issues/834

**Comment by n-rodriguez** [comment]
hi there! any news?

**Comment by n-rodriguez** [comment]
Hi there! Any change to get this merged?

**Comment by n-rodriguez** [comment]
ping @ctran

**Comment by n-rodriguez** [comment]
ping @ctran 

About the failing specs : there must be some leaking states somewhere. Errors now appear because of https://github.com/ctran/annotate_models/pull/787.

**Comment by n-rodriguez** [comment]
ping @ctran

**Comment by ctran** [comment]
I think there's something else causing the CI failures, not your changes.  I've been trying to figure out where the problem lies but it's taking me some time since I've been away from this for some time.

**Comment by n-rodriguez** [comment]
ping @ctran

**Comment by ctran** [comment]
Hi, the CI issue is now fixed on the `develop` branch.  Did you rebase with the recent changes?

**Review by ctran — APPROVED** [review]

**Comment by n-rodriguez** [comment]
Thank you!

**Pull request merged**
