### PR TITLE
Added new gems.

### PR DESCRIPTION
**Pull request by ryanfox1985**
Added byebug for debugging.

### CODE REVIEW

**Comment by ctran** [comment]
Could you explain why we need this?

**Comment by ryanfox1985** [comment]
Hi @ctran,

the gem byebug is works very well to debug the gem. Putting byebug in the code you are creating a breakpoint and you have a shell (better than puts xD). 

Let me fix the tests before merge. 

Regards.

**Comment by ryanfox1985** [comment]
@ctran the merge is baddddd, don't worry I will rebase and fix.

**Comment by ryanfox1985** [comment]
@ctran can you add this:

`bundle exec rubocop && bundle exec rspec` 

to the semaphoreCI?

**Comment by ryanfox1985** [comment]
@ctran ready to merge.

**Pull request merged**
