### PR TITLE
Routes markdown

### LINKED ISSUE #178: Annotating routes doesn't support markdown option
Running Rails 4.1 & annotate 2.6.3, and created the rake task. I've edited it to enable format_markdown, but it seems running `bin/rake annotate_routes` doesn't honor the option. The model annotation works at least.

### PR DESCRIPTION
**Pull request by ryanfox1985**
Implemented routes in markdown, closes #178

### CODE REVIEW

**Comment by ctran** [comment]
Could you remove the change in .rubocop_tody.yml?  It's causing conflicts.

**Comment by ryanfox1985** [comment]
rebased

**Comment by ryanfox1985** [comment]
I think that I have a mistake in markdown. Let me check.

**Comment by ryanfox1985** [comment]
Yes, I corrected, the element in the table can has the char pipe `|` and has a trouble with the table markdown. Now it's ready.

**Pull request merged**
