### PR TITLE
rubocop friendly template

### PR DESCRIPTION
**Pull request by roflomglol**
Resubmitted as requested. I've rebased from latest develop branch so there is no merge conflict anymore. (I hope I didn't miss anything :) )

### CODE REVIEW

**Comment by ctran** [comment]
You missed the "exclude_scaffolds" option :-)

**Comment by roflomglol** [comment]
Damn, I knew that +26 -27 means something :D

**Comment by roflomglol** [comment]
I was about to fix that. :< Sorry! :)

**Comment by ctran** [comment]
No problem, I manually fixed after the PR.  Thanks

**Pull request merged**
